#!/bin/bash

set -e

# Get secrets from 1Password
fields=$(op item get "kafka-webhook-bridge" --format json --vault Environments || exit 1)

echo "# Generated by get_env_vars.sh - DO NOT EDIT"
echo "# Run this script to update values: aws/get_env_vars.sh > .envrc"

# Process 1Password fields
while IFS= read -r row; do
    _jq() {
        echo "${row}" | base64 --decode | jq -r "${1}"
    }
    key=$(_jq '.label')
    value=$(_jq '.value')

    # Convert 1Password field names to environment variable names
    case "$key" in
        "KAFKA_USERNAME")
            echo "export KAFKA_USERNAME='${value}'"
            ;;
        "KAFKA_PASSWORD")
            echo "export KAFKA_PASSWORD='${value}'"
            ;;
        "WEBHOOK_USERNAME")
            echo "export WEBHOOK_USERNAME='${value}'"
            ;;
        "WEBHOOK_PASSWORD")
            echo "export WEBHOOK_PASSWORD='${value}'"
            ;;
        "HOSTED_ZONE_ID")
            echo "export HOSTED_ZONE_ID='${value}'"
            ;;
        *)
            printf "# skipping unused field %s\n" "$key"
            ;;
    esac
done < <(echo "${fields}" | jq -r '.fields[] | @base64') 